const test=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');
function renderer(){const nodes=new Map();const node=id=>{if(!nodes.has(id))nodes.set(id,{classList:{add(){},remove(){},toggle(){}},style:{},appendChild(){},replaceChildren(){},setAttribute(){},textContent:'',checked:false});return nodes.get(id)};const ctx=vm.createContext({window:{},document:{getElementById:node,createElement:()=>node(Math.random())},console,WebSocket:{OPEN:1},setTimeout:()=>0,clearTimeout(){},URL,Blob,Date});vm.runInContext(fs.readFileSync('engine/phantom/webui/app.js','utf8').replace(/^boot\(\);$/m,''),ctx);return {ctx,node,run:s=>vm.runInContext(s,ctx)}}
test('commands fail visibly while disconnected',()=>{const r=renderer();assert.equal(r.run('send({cmd:"clear"})'),false);assert.match(r.node('errorText').textContent,/not sent.*disconnected/)});
test('coordinate parser rejects out of range and accepts maps coordinates',()=>{const r=renderer();assert.equal(r.run('parseCoords("91, 0")'),null);assert.equal(r.run('parseCoords("1, 181")'),null);assert.equal(r.run('parseCoords("https://maps/@40.5,-73.2,12z").lon'),-73.2)});
test('transport profile survives custom speed selection',()=>{const r=renderer();r.node('speedSlider').style.setProperty=()=>{};r.node('speedSlider').max=1000;r.run('applyPreset("walk");applyPreset("custom")');assert.equal(r.run('state.profile'),'walking')});
test('search input never schedules geocoding',()=>{const source=fs.readFileSync('engine/phantom/webui/app.js','utf8');assert.doesNotMatch(source,/setTimeout\([^\n]*geocode/);assert.doesNotMatch(source,/fetch\(`https:\/\/nominatim/)});
test('normal and advanced speed remain within backend bounds',()=>{const r=renderer();r.node('speedSlider').style.setProperty=()=>{};r.run('setMph(1e16)');assert.equal(r.node('speedMph').value,1000);r.node('ludicrous').checked=true;r.run('setMph(1e16)');assert.equal(r.node('speedMph').value,22369);assert.ok(r.run('currentMph()/MPS_TO_MPH')<=10000)});
test('paused and resumed events update session dashboard',()=>{const r=renderer();r.run('handle({type:"paused"})');assert.equal(r.run('state.paused'),true);assert.match(r.node('sessionConnection').textContent,/paused/);r.run('handle({type:"resumed"})');assert.equal(r.run('state.paused'),false);assert.match(r.node('sessionConnection').textContent,/resumed/)});
test('socket closure clears active control and interpolation',()=>{const r=renderer();r.ctx.WebSocket=class {static OPEN=1};r.ctx.location={host:'localhost:1'};r.ctx.clearInterval=()=>{};r.run('state.ready=true;state.connected=true;state.moving=true;state.prev={lat:1,lon:1};state.targetPt={lat:2,lon:2};connect();ws.onclose()');assert.equal(r.run('state.ready'),false);assert.equal(r.run('state.moving'),false);assert.equal(r.run('state.targetPt'),null);assert.match(r.node('sessionConnection').textContent,/Disconnected/);assert.equal(r.node('startBtn').disabled,true)});
test('failed route extension removes pending stop while preserving movement',()=>{const r=renderer();r.run('renderWaypoints=()=>{};state.moving=true;state.pendingAddStop={lat:3,lon:4};state.waypoints=[{lat:1,lon:2},state.pendingAddStop];handle({type:"error",cmd:"add_stop",code:"routing_failed",message:"Route unavailable"})');assert.equal(r.run('state.moving'),true);assert.equal(r.run('state.waypoints.length'),1);assert.equal(r.run('state.pendingAddStop'),null)});
test('saved places use active device query',async()=>{const r=renderer();let called='';r.ctx.fetch=async path=>{called=path;return {ok:true,json:async()=>({bookmarks:[],recents:[]})}};await r.run('state.deviceId="phone A";loadPlaces()');assert.equal(called,'/api/places?udid=phone%20A')});
test('repeated fixes preserve paused dashboard state',()=>{const r=renderer();r.run('onFix=()=>{};state.paused=true;handle({type:"fix",lat:1,lon:2});handle({type:"fix",lat:1,lon:2})');assert.match(r.node('sessionConnection').textContent,/Paused/)});
test('save response from previous device cannot replace visible library',async()=>{const r=renderer();let resolve;r.ctx.fetch=()=>new Promise(done=>resolve=done);const pending=r.run('state.deviceId="A";persistLibrary([{id:"a"}])');r.run('state.deviceId="B";libraryGeneration++;library=[{id:"b"}];libraryBusy=true');resolve({ok:true});await pending;assert.equal(r.run('library[0].id'),'b');assert.equal(r.run('libraryBusy'),true)});

test('satellite tile origins are permitted by the shipped CSP',()=>{
  const html=fs.readFileSync('engine/phantom/webui/index.html','utf8');
  const script=fs.readFileSync('engine/phantom/webui/app.js','utf8');
  const policy=html.match(/http-equiv="Content-Security-Policy" content="([^"]+)"/)[1];
  const connect=policy.split(';').map(s=>s.trim()).find(s=>s.startsWith('connect-src ')).split(/\s+/).slice(1);
  const tiles=script.match(/tiles:\s*\["([^"]+)"/)[1];
  assert.ok(connect.includes(new URL(tiles).origin),'Satellite fetch must be allowed in the actual HTML policy');
  assert.ok(!connect.includes('*'),'Keep the policy restricted to explicit origins');
});
